name: ilovecleaning
favicon: null
layout_spectrum: 0.74501
typography_spectrum: 0.24259
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fff45c'
    - '#00a5b3'
    - '#57b079'
    - '#78c7cc'
  brandStrength: 0.5
  lightness: 0.4968897632788867
  saturation: 0.75
  rhythmicContrast: 0.17692175530828536
purpose: []
